// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionResult {
    "success": boolean;
    "message": string;
    "warning": string;
    "branch": string;
}

export interface LinkResult {
    "linked": boolean;
    "message": string;
    "warning": string;
    "branch": string;
    "lastCommit": string;
}

/**
 * PullResult reports the outcome of fetching the remote snapshot. StagingPath
 * points at the materialized encrypted layout; Temporary indicates ownership.
 */
export interface PullResult {
    "linked": boolean;
    "message": string;
    "warning": string;
    "branch": string;
    "lastCommit": string;
    "stagingPath": string;
    "temporary": boolean;
    "upToDate": boolean;
}

/**
 * PushResult reports the outcome of pushing the local vault snapshot to the
 * remote repository.
 */
export interface PushResult {
    "linked": boolean;
    "message": string;
    "warning": string;
    "branch": string;
    "lastCommit": string;
    "upToDate": boolean;
}

/**
 * SyncSettings is the device-local configuration exposed to the application
 * frontend. The SSH key bytes are never read into or returned by this type.
 */
export interface SyncSettings {
    "formatVersion": number;
    "vaultId": string;
    "provider": string;
    "repositorySsh": string;
    "privateKeyPath": string;
    "branch": string;
    "repositoryPrivate": boolean;
    "linked": boolean;
    "lastSyncedAt": number;
    "lastSnapshotRev": string;
    "lastCommit": string;
}
