sonar.organization=vbenevides
sonar.projectKey=VBenevides_cipherleaf
sonar.sources=main.go,internal,frontend/src
sonar.tests=frontend/tests
sonar.test.inclusions=frontend/tests/**/*.ts,**/*_test.go
sonar.go.coverage.reportPaths=coverage/go.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.qualitygate.wait=true

sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/vendor/**,\
**/coverage/**,\
**/*_test.go
