package app

import (
	"testing"

	"cipherleaf/internal/githubsync"
	"cipherleaf/internal/vault"
)

func TestVaultServiceLockedPaths(t *testing.T) {
	service := NewVaultService()
	service.SetApp(nil)

	if !service.GetSession().Locked {
		t.Fatal("new service should start locked")
	}
	service.QuitApplication()
	_, _ = service.GetApplicationStatistics()
	_, _ = service.ListInstalledFonts()
	_, _ = service.SelectVaultFolder()
	_, _ = service.SelectVaultDestinationFolder()
	_, _ = service.SelectMarkdownFolder("select")
	_, _ = service.SelectGitHubSSHKey()
	_, _ = service.SelectAttachmentFile()
	_, _ = service.GenerateVaultSecret()
	_ = service.CopyVaultSecret("invalid")
	_, _ = service.OpenVault("/missing", "invalid")
	_, _ = service.GetLastVaultPath()
	_, _ = service.ListRecentVaultPaths()
	_ = service.RemoveRecentVaultPath("")
	_, _ = service.GetLastSession()
	_ = service.RememberTheme("dark")
	_ = service.RememberVaultSecret("secret")
	_ = service.ForgetVaultSecret()
	_, _ = service.TryUnlockRemembered()
	_, _ = service.CloseVault()
	_, _ = service.GetVaultStatistics()
	_, _ = service.GetTimeTrackingCatalog()
	_, _ = service.CreateClient("client")
	_, _ = service.RenameClient("client", "renamed")
	_, _ = service.ArchiveClient("client")
	_, _ = service.RestoreClient("client")
	_ = service.DeleteClient("client")
	_, _ = service.CreateProject("project")
	_, _ = service.CreateProjectForClient("project", "client")
	_, _ = service.RenameProject("project", "renamed")
	_, _ = service.UpdateProject("project", "renamed", "client")
	_, _ = service.ArchiveProject("project")
	_, _ = service.RestoreProject("project")
	_ = service.DeleteProject("project")
	_, _ = service.CreateTag("tag")
	_, _ = service.RenameTag("tag", "renamed")
	_, _ = service.ArchiveTag("tag")
	_, _ = service.RestoreTag("tag")
	_ = service.DeleteTag("tag")
	_, _ = service.StartTimeEntry("task", "project", nil)
	_, _ = service.StartTimeEntryForClient("task", "client", "project", nil)
	_, _ = service.GetActiveTimeEntry()
	_, _ = service.FinishActiveTimeEntry()
	_, _ = service.UpdateTimeEntry("entry", "task", "project", nil, "", "")
	_, _ = service.UpdateTimeEntryForClient("entry", "task", "client", "project", nil, "", "")
	_ = service.DeleteTimeEntry("entry")
	_, _ = service.ListTimeEntries("", "", vault.TimeEntryFilters{})
	_, _ = service.GetTimeDashboard("", "", vault.TimeEntryFilters{})
	_, _ = service.ListTimeDashboardGroupEntries("", "", "", vault.TimeEntryFilters{})
	_, _ = service.ListTimeTrackingConflicts()
	_ = service.ResolveTimeTrackingConflict("conflict")
	_, _ = service.ListNotes()
	_, _ = service.ListFolders()
	_, _ = service.CreateFolder("folder", "")
	_, _ = service.RenameFolder("folder", "renamed")
	_ = service.DeleteFolder("folder")
	_ = service.ReorderFolders(nil)
	_, _ = service.MoveFolder("folder", "")
	_, _ = service.SetFolderHidden("folder", true)
	_, _ = service.LockFolder("folder", "password")
	_, _ = service.UnlockFolder("folder", "password")
	_ = service.CheckFolderPassword("folder", "password")
	_ = service.LockFolderSession("folder")
	_, _ = service.SetFolderSortMode("folder", "title")
	_, _ = service.CreateNote("note")
	_, _ = service.CreateNoteInFolder("note", "folder")
	_, _ = service.MoveNote("note", "folder")
	_ = service.ReorderNotes("folder", nil)
	_, _ = service.GetNote("note")
	_, _ = service.SaveNote("note", "title", "content")
	_, _ = service.SaveImageAttachment("note", "invalid")
	_, _ = service.GetAttachment("note", "attachment")
	_, _ = service.ImportFileAttachment("note", "/missing")
	_, _ = service.ExportFileAttachment("note", "attachment", t.TempDir())
	_, _ = service.ListFileAttachments("note")
	_, _ = service.ReadClipboardImage()
	_ = service.DeleteNote("note")
	_, _ = service.ListTrash()
	_ = service.RestoreTrashItem("note", "note")
	_ = service.PermanentlyDeleteTrashItem("note", "note")
	_, _ = service.ListNoteVersions("note")
	_ = service.CleanHistory()
	_, _ = service.RestoreNoteVersion("note", 1)
	_, _ = service.ImportMarkdown("/missing")
	_, _ = service.ExportMarkdown("/missing")
	_, _ = service.ResolveNoteReference("note")
	_, _ = service.ListBacklinks("note")
	_, _ = service.FindInNotes("query", false, false)
	_, _ = service.ReplaceAcrossNotes("find", "replace", nil, false, false)
	_, _ = service.GetVaultSettings()
	_, _ = service.SaveVaultSettings(vault.VaultSettings{})
	_, _ = service.GetSyncSettings()
	_, _ = service.TestGitHubConnection(githubsync.SyncSettings{})
	_, _ = service.LinkGitHubVault(githubsync.SyncSettings{})
	_, _ = service.PullAndLinkGitHubVault(githubsync.SyncSettings{})
	_ = service.UnlinkGitHubSync()
	_ = service.OpenGitTerminal()
	_, _ = service.SyncNow()
	_, _ = service.ForcePushNow()
}
