// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as githubsync$0 from "../githubsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "../vault/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckFolderPassword(id: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(883597332, id, password);
}

export function CloneGitHubVault(parentPath: string, name: string, repositorySSH: string, privateKeyPath: string, branch: string, secret: string, repositoryPrivate: boolean): $CancellablePromise<$models.CloneVaultResult> {
    return $Call.ByID(3036187677, parentPath, name, repositorySSH, privateKeyPath, branch, secret, repositoryPrivate);
}

export function CloseVault(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(4139522503);
}

export function CopyVaultSecret(secret: string): $CancellablePromise<void> {
    return $Call.ByID(3868872474, secret);
}

export function CreateFolder(name: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(239305947, name);
}

export function CreateNote(title: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(2911480927, title);
}

export function CreateNoteInFolder(title: string, folderID: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(715955408, title, folderID);
}

export function CreateVault(parentPath: string, name: string, secret: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(814546393, parentPath, name, secret);
}

export function DeleteAttachment(noteID: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(3811592289, noteID, id);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(925796928, id);
}

export function DeleteNote(id: string): $CancellablePromise<void> {
    return $Call.ByID(2625750688, id);
}

export function FindInNotes(query: string): $CancellablePromise<vault$0.FindMatch[] | null> {
    return $Call.ByID(991868496, query);
}

/**
 * ForcePushNow overwrites the linked remote branch with the current local
 * encrypted vault snapshot after the user explicitly confirms conflict loss.
 */
export function ForcePushNow(): $CancellablePromise<githubsync$0.PushResult> {
    return $Call.ByID(2357438882);
}

/**
 * vault from the OS keychain. It is a no-op when the vault is not linked to
 * a keychain entry.
 */
export function ForgetVaultSecret(): $CancellablePromise<void> {
    return $Call.ByID(1221274530);
}

export function GenerateVaultSecret(): $CancellablePromise<string> {
    return $Call.ByID(3315011432);
}

export function GetAttachment(noteID: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(115494468, noteID, id);
}

export function GetLastSession(): $CancellablePromise<$models.LastSession> {
    return $Call.ByID(3632998615);
}

export function GetLastVaultPath(): $CancellablePromise<string> {
    return $Call.ByID(3809458984);
}

export function GetNote(id: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(1503400201, id);
}

export function GetSession(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(355925843);
}

export function GetSyncSettings(): $CancellablePromise<githubsync$0.SyncSettings> {
    return $Call.ByID(2923257755);
}

export function LinkGitHubVault(settings: githubsync$0.SyncSettings): $CancellablePromise<githubsync$0.LinkResult> {
    return $Call.ByID(974300788, settings);
}

export function ListBacklinks(noteID: string): $CancellablePromise<vault$0.FindMatch[] | null> {
    return $Call.ByID(1268925393, noteID);
}

export function ListFolders(): $CancellablePromise<vault$0.Folder[] | null> {
    return $Call.ByID(220507736);
}

export function ListNotes(): $CancellablePromise<vault$0.NoteSummary[] | null> {
    return $Call.ByID(888598820);
}

export function LockFolder(id: string, password: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(1628193172, id, password);
}

export function LockVault(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(3801710036);
}

export function MoveNote(id: string, folderID: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(4129360186, id, folderID);
}

export function OpenVault(path: string, secret: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(1998151597, path, secret);
}

/**
 * OpenVaultRemembered opens path with its unexpired secret from the OS
 * keychain. This also supports switching directly between remembered vaults.
 */
export function OpenVaultRemembered(path: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(910528891, path);
}

export function PullAndLinkGitHubVault(settings: githubsync$0.SyncSettings): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(866409854, settings);
}

/**
 * PullNow pulls and merges the remote vault snapshot without pushing back.
 */
export function PullNow(): $CancellablePromise<vault$0.MergeResult> {
    return $Call.ByID(2641264576);
}

export function QuitApplication(): $CancellablePromise<void> {
    return $Call.ByID(1295474446);
}

export function ReadClipboardImage(): $CancellablePromise<string> {
    return $Call.ByID(242574664);
}

export function RememberTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(592066557, theme);
}

/**
 * RememberVaultSecret stores the open vault's secret in the OS keychain so
 * the user does not have to paste it again for the configured TTL. It must
 * be called only after a successful Open so the secret is known to be valid.
 */
export function RememberVaultSecret(): $CancellablePromise<void> {
    return $Call.ByID(4089226512);
}

export function RenameFolder(id: string, name: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(2836532501, id, name);
}

export function RenameVault(newName: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(1978051175, newName);
}

export function ReorderFolders(orderedIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3012602063, orderedIDs);
}

export function ReorderNotes(folderID: string, orderedIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2800466995, folderID, orderedIDs);
}

export function ReplaceAcrossNotes(find: string, replace: string, noteIDs: string[] | null): $CancellablePromise<vault$0.ReplaceResult> {
    return $Call.ByID(1932071061, find, replace, noteIDs);
}

export function ResolveNoteReference(reference: string): $CancellablePromise<vault$0.NoteSummary> {
    return $Call.ByID(4068969958, reference);
}

export function SaveAttachment(noteID: string, webpBase64: string): $CancellablePromise<string> {
    return $Call.ByID(2496789391, noteID, webpBase64);
}

export function SaveImageAttachment(noteID: string, imageDataURL: string): $CancellablePromise<string> {
    return $Call.ByID(1556359170, noteID, imageDataURL);
}

export function SaveNote(id: string, title: string, content: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(2770680190, id, title, content);
}

export function SearchNotes(query: string): $CancellablePromise<vault$0.NoteSummary[] | null> {
    return $Call.ByID(1370302028, query);
}

export function SelectGitHubSSHKey(): $CancellablePromise<string> {
    return $Call.ByID(233117765);
}

export function SelectVaultDestinationFolder(): $CancellablePromise<string> {
    return $Call.ByID(2686336143);
}

export function SelectVaultFolder(): $CancellablePromise<string> {
    return $Call.ByID(2449201265);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3509715860, app);
}

export function SetFolderHidden(id: string, hidden: boolean): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(3809884713, id, hidden);
}

export function SetFolderSortMode(id: string, mode: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(3310669214, id, mode);
}

/**
 * SyncNow performs a manual pull-merge-push against the linked GitHub
 * repository. Local notes newer than their remote counterpart are preserved;
 * remote notes newer than local replace the local copy.
 */
export function SyncNow(): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(3410023864);
}

export function TestGitHubConnection(settings: githubsync$0.SyncSettings): $CancellablePromise<githubsync$0.ConnectionResult> {
    return $Call.ByID(1416189504, settings);
}

/**
 * TryUnlockRemembered attempts to unlock the last opened vault using a
 * secret remembered in the OS keychain. It returns ErrNoRememberedSecret
 * (or any other error) when the user must enter the secret manually; a
 * successful return yields an unlocked Session.
 */
export function TryUnlockRemembered(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(3849116738);
}

export function UnlinkGitHubSync(): $CancellablePromise<void> {
    return $Call.ByID(3056730288);
}

export function UnlockFolder(id: string, password: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(3266411627, id, password);
}
