// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as githubsync$0 from "../githubsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "../vault/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ArchiveClient(id: string): $CancellablePromise<vault$0.TimeClient> {
    return $Call.ByID(2587329448, id);
}

export function ArchiveProject(id: string): $CancellablePromise<vault$0.TimeProject> {
    return $Call.ByID(4168033684, id);
}

export function ArchiveTag(id: string): $CancellablePromise<vault$0.TimeTag> {
    return $Call.ByID(2265665421, id);
}

export function CheckFolderPassword(id: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(883597332, id, password);
}

export function CloneGitHubVault(parentPath: string, name: string, repositorySSH: string, privateKeyPath: string, branch: string, secret: string, repositoryPrivate: boolean): $CancellablePromise<$models.CloneVaultResult> {
    return $Call.ByID(3036187677, parentPath, name, repositorySSH, privateKeyPath, branch, secret, repositoryPrivate);
}

export function CloseVault(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(4139522503);
}

export function CopyVaultSecret(secret: string): $CancellablePromise<void> {
    return $Call.ByID(3868872474, secret);
}

export function CreateClient(name: string): $CancellablePromise<vault$0.TimeClient> {
    return $Call.ByID(4062770880, name);
}

export function CreateFolder(name: string, parentID: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(239305947, name, parentID);
}

export function CreateNote(title: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(2911480927, title);
}

export function CreateNoteInFolder(title: string, folderID: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(715955408, title, folderID);
}

export function CreateProject(name: string): $CancellablePromise<vault$0.TimeProject> {
    return $Call.ByID(2039739724, name);
}

export function CreateProjectForClient(name: string, clientID: string): $CancellablePromise<vault$0.TimeProject> {
    return $Call.ByID(1966438356, name, clientID);
}

export function CreateTag(name: string): $CancellablePromise<vault$0.TimeTag> {
    return $Call.ByID(1532899813, name);
}

export function CreateVault(parentPath: string, name: string, secret: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(814546393, parentPath, name, secret);
}

export function DeleteAttachment(noteID: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(3811592289, noteID, id);
}

export function DeleteClient(id: string): $CancellablePromise<void> {
    return $Call.ByID(25439555, id);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(925796928, id);
}

export function DeleteNote(id: string): $CancellablePromise<void> {
    return $Call.ByID(2625750688, id);
}

export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(2717384377, id);
}

export function DeleteTag(id: string): $CancellablePromise<void> {
    return $Call.ByID(1642915612, id);
}

export function DeleteTimeEntry(id: string): $CancellablePromise<void> {
    return $Call.ByID(2270152867, id);
}

export function ExportFileAttachment(noteID: string, id: string, destination: string): $CancellablePromise<string> {
    return $Call.ByID(40245150, noteID, id, destination);
}

export function ExportMarkdown(path: string): $CancellablePromise<vault$0.PortabilityResult> {
    return $Call.ByID(1927621820, path);
}

export function FindInNotes(query: string, caseSensitive: boolean, wholeWord: boolean): $CancellablePromise<vault$0.FindMatch[] | null> {
    return $Call.ByID(991868496, query, caseSensitive, wholeWord);
}

export function FinishActiveTimeEntry(): $CancellablePromise<vault$0.TimeEntry> {
    return $Call.ByID(3424202037);
}

/**
 * ForcePushNow overwrites the linked remote branch with the current local
 * encrypted vault snapshot after the user explicitly confirms conflict loss.
 */
export function ForcePushNow(): $CancellablePromise<githubsync$0.PushResult> {
    return $Call.ByID(2357438882);
}

/**
 * vault from the OS keychain. It is a no-op when the vault is not linked to
 * a keychain entry.
 */
export function ForgetVaultSecret(): $CancellablePromise<void> {
    return $Call.ByID(1221274530);
}

export function GenerateVaultSecret(): $CancellablePromise<string> {
    return $Call.ByID(3315011432);
}

export function GetActiveTimeEntry(): $CancellablePromise<vault$0.TimeEntry | null> {
    return $Call.ByID(2155705394);
}

export function GetApplicationStatistics(): $CancellablePromise<$models.ApplicationStatistics> {
    return $Call.ByID(1301789830);
}

export function GetAttachment(noteID: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(115494468, noteID, id);
}

export function GetLastSession(): $CancellablePromise<$models.LastSession> {
    return $Call.ByID(3632998615);
}

export function GetLastVaultPath(): $CancellablePromise<string> {
    return $Call.ByID(3809458984);
}

export function GetNote(id: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(1503400201, id);
}

export function GetSession(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(355925843);
}

export function GetSyncSettings(): $CancellablePromise<githubsync$0.SyncSettings> {
    return $Call.ByID(2923257755);
}

export function GetTimeDashboard(startUTC: string, endUTC: string, filters: vault$0.TimeEntryFilters): $CancellablePromise<vault$0.TimeDashboard> {
    return $Call.ByID(259867052, startUTC, endUTC, filters);
}

export function GetTimeTrackingCatalog(): $CancellablePromise<vault$0.TimeTrackingCatalog> {
    return $Call.ByID(308561412);
}

export function GetVaultSettings(): $CancellablePromise<vault$0.VaultSettings> {
    return $Call.ByID(4079532670);
}

export function GetVaultStatistics(): $CancellablePromise<vault$0.VaultStatistics> {
    return $Call.ByID(3277829736);
}

export function ImportFileAttachment(noteID: string, path: string): $CancellablePromise<vault$0.AttachmentInfo> {
    return $Call.ByID(2182536893, noteID, path);
}

export function ImportMarkdown(path: string): $CancellablePromise<vault$0.PortabilityResult> {
    return $Call.ByID(1577812963, path);
}

export function LinkGitHubVault(settings: githubsync$0.SyncSettings): $CancellablePromise<githubsync$0.LinkResult> {
    return $Call.ByID(974300788, settings);
}

export function ListBacklinks(noteID: string): $CancellablePromise<vault$0.FindMatch[] | null> {
    return $Call.ByID(1268925393, noteID);
}

export function ListFileAttachments(noteID: string): $CancellablePromise<vault$0.AttachmentInfo[] | null> {
    return $Call.ByID(4116603909, noteID);
}

export function ListFolders(): $CancellablePromise<vault$0.Folder[] | null> {
    return $Call.ByID(220507736);
}

export function ListNoteVersions(id: string): $CancellablePromise<vault$0.NoteVersion[] | null> {
    return $Call.ByID(2533964502, id);
}

export function ListNotes(): $CancellablePromise<vault$0.NoteSummary[] | null> {
    return $Call.ByID(888598820);
}

export function ListRecentVaultPaths(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1694639620);
}

export function ListTimeDashboardGroupEntries(name: string, startUTC: string, endUTC: string, filters: vault$0.TimeEntryFilters): $CancellablePromise<vault$0.TimeEntryRangeItem[] | null> {
    return $Call.ByID(516244023, name, startUTC, endUTC, filters);
}

export function ListTimeEntries(startUTC: string, endUTC: string, filters: vault$0.TimeEntryFilters): $CancellablePromise<vault$0.TimeEntryRangeResult> {
    return $Call.ByID(1766611694, startUTC, endUTC, filters);
}

export function ListTimeTrackingConflicts(): $CancellablePromise<vault$0.TimeTrackingConflict[] | null> {
    return $Call.ByID(76659230);
}

export function ListTrash(): $CancellablePromise<vault$0.TrashItem[] | null> {
    return $Call.ByID(3351323131);
}

export function LockFolder(id: string, password: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(1628193172, id, password);
}

export function LockFolderSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3716022032, id);
}

export function LockVault(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(3801710036);
}

export function MoveFolder(id: string, parentID: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(4062408878, id, parentID);
}

export function MoveNote(id: string, folderID: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(4129360186, id, folderID);
}

/**
 * OpenGitTerminal opens the system terminal at this vault's encrypted Git checkout.
 */
export function OpenGitTerminal(): $CancellablePromise<void> {
    return $Call.ByID(3947699405);
}

export function OpenVault(path: string, secret: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(1998151597, path, secret);
}

/**
 * OpenVaultRemembered opens path with its unexpired secret from the OS
 * keychain. This also supports switching directly between remembered vaults.
 */
export function OpenVaultRemembered(path: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(910528891, path);
}

export function PermanentlyDeleteTrashItem(kind: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1655843432, kind, id);
}

export function PullAndLinkGitHubVault(settings: githubsync$0.SyncSettings): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(866409854, settings);
}

export function QuitApplication(): $CancellablePromise<void> {
    return $Call.ByID(1295474446);
}

export function ReadClipboardImage(): $CancellablePromise<string> {
    return $Call.ByID(242574664);
}

export function RememberTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(592066557, theme);
}

/**
 * RememberVaultSecret stores the open vault's secret in the OS keychain so
 * the user does not have to paste it again for the configured TTL. It must
 * be called only after a successful Open so the secret is known to be valid.
 */
export function RememberVaultSecret(): $CancellablePromise<void> {
    return $Call.ByID(4089226512);
}

export function RenameClient(id: string, name: string): $CancellablePromise<vault$0.TimeClient> {
    return $Call.ByID(975015718, id, name);
}

export function RenameFolder(id: string, name: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(2836532501, id, name);
}

export function RenameProject(id: string, name: string): $CancellablePromise<vault$0.TimeProject> {
    return $Call.ByID(1556478150, id, name);
}

export function RenameTag(id: string, name: string): $CancellablePromise<vault$0.TimeTag> {
    return $Call.ByID(2522910107, id, name);
}

export function RenameVault(newName: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(1978051175, newName);
}

export function ReorderFolders(orderedIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3012602063, orderedIDs);
}

export function ReorderNotes(folderID: string, orderedIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2800466995, folderID, orderedIDs);
}

export function ReplaceAcrossNotes(find: string, replace: string, noteIDs: string[] | null, caseSensitive: boolean, wholeWord: boolean): $CancellablePromise<vault$0.ReplaceResult> {
    return $Call.ByID(1932071061, find, replace, noteIDs, caseSensitive, wholeWord);
}

export function ResolveNoteReference(reference: string): $CancellablePromise<vault$0.NoteSummary> {
    return $Call.ByID(4068969958, reference);
}

export function ResolveTimeTrackingConflict(id: string): $CancellablePromise<void> {
    return $Call.ByID(2018735579, id);
}

export function RestoreClient(id: string): $CancellablePromise<vault$0.TimeClient> {
    return $Call.ByID(2997005664, id);
}

export function RestoreNoteVersion(id: string, revision: number): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(3216968481, id, revision);
}

export function RestoreProject(id: string): $CancellablePromise<vault$0.TimeProject> {
    return $Call.ByID(791124588, id);
}

export function RestoreTag(id: string): $CancellablePromise<vault$0.TimeTag> {
    return $Call.ByID(47787781, id);
}

export function RestoreTrashItem(kind: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(3441570684, kind, id);
}

export function SaveImageAttachment(noteID: string, imageDataURL: string): $CancellablePromise<string> {
    return $Call.ByID(1556359170, noteID, imageDataURL);
}

export function SaveNote(id: string, title: string, content: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(2770680190, id, title, content);
}

export function SaveVaultSettings(settings: vault$0.VaultSettings): $CancellablePromise<vault$0.VaultSettings> {
    return $Call.ByID(3499492715, settings);
}

export function SelectAttachmentFile(): $CancellablePromise<string> {
    return $Call.ByID(3438204788);
}

export function SelectGitHubSSHKey(): $CancellablePromise<string> {
    return $Call.ByID(233117765);
}

export function SelectMarkdownFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(1224618098, title);
}

export function SelectVaultDestinationFolder(): $CancellablePromise<string> {
    return $Call.ByID(2686336143);
}

export function SelectVaultFolder(): $CancellablePromise<string> {
    return $Call.ByID(2449201265);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3509715860, app);
}

export function SetFolderHidden(id: string, hidden: boolean): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(3809884713, id, hidden);
}

export function SetFolderSortMode(id: string, mode: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(3310669214, id, mode);
}

export function StartTimeEntry(name: string, projectID: string, tagIDs: string[] | null): $CancellablePromise<vault$0.TimeEntry> {
    return $Call.ByID(1787308032, name, projectID, tagIDs);
}

export function StartTimeEntryForClient(name: string, clientID: string, projectID: string, tagIDs: string[] | null): $CancellablePromise<vault$0.TimeEntry> {
    return $Call.ByID(4267492704, name, clientID, projectID, tagIDs);
}

/**
 * SyncNow performs a manual pull-merge-push against the linked GitHub
 * repository. Local notes newer than their remote counterpart are preserved;
 * remote notes newer than local replace the local copy.
 */
export function SyncNow(): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(3410023864);
}

export function TestGitHubConnection(settings: githubsync$0.SyncSettings): $CancellablePromise<githubsync$0.ConnectionResult> {
    return $Call.ByID(1416189504, settings);
}

/**
 * TryUnlockRemembered attempts to unlock the last opened vault using a
 * secret remembered in the OS keychain. It returns ErrNoRememberedSecret
 * (or any other error) when the user must enter the secret manually; a
 * successful return yields an unlocked Session.
 */
export function TryUnlockRemembered(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(3849116738);
}

export function UnlinkGitHubSync(): $CancellablePromise<void> {
    return $Call.ByID(3056730288);
}

export function UnlockFolder(id: string, password: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(3266411627, id, password);
}

export function UpdateProject(id: string, name: string, clientID: string): $CancellablePromise<vault$0.TimeProject> {
    return $Call.ByID(3548001575, id, name, clientID);
}

export function UpdateTimeEntry(id: string, name: string, projectID: string, tagIDs: string[] | null, startedAtUTC: string, endedAtUTC: string): $CancellablePromise<vault$0.TimeEntry> {
    return $Call.ByID(1385339193, id, name, projectID, tagIDs, startedAtUTC, endedAtUTC);
}

export function UpdateTimeEntryForClient(id: string, name: string, clientID: string, projectID: string, tagIDs: string[] | null, startedAtUTC: string, endedAtUTC: string): $CancellablePromise<vault$0.TimeEntry> {
    return $Call.ByID(1432466107, id, name, clientID, projectID, tagIDs, startedAtUTC, endedAtUTC);
}
