// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AttachmentInfo {
    "id": string;
    "filename": string;
    "mimeType": string;
    "size": number;
}

/**
 * FindMatch describes a single occurrence of a query inside a note.
 */
export interface FindMatch {
    "noteId": string;
    "title": string;
    "folderId": string;
    "field": string;
    "snippet": string;
    "offset": number;
    "matchLength": number;
    "utf16Offset": number;
    "utf16MatchLength": number;
}

export interface Folder {
    "id": string;
    "name": string;
    "parentId"?: string;
    "order": number;
    "hidden"?: boolean;
    "locked"?: boolean;
    "lockPasswordHash"?: string;
    "sortMode"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export interface MergeConflict {
    "localNoteId": string;
    "remoteNoteId": string;
    "title": string;
    "message": string;
    "localContent": string;
    "remoteContent": string;
}

/**
 * MergeResult summarizes a pull merge between the remote and local vault.
 */
export interface MergeResult {
    "pulledNotes": number;
    "updatedNotes": number;
    "deletedNotes": number;
    "pulledFolders": number;
    "deletedFolders": number;
    "updatedSettings": boolean;
    "upToDate": boolean;
    "conflicts"?: MergeConflict[] | null;
    "trackingConflicts"?: TimeTrackingConflict[] | null;
}

export interface Note {
    "id": string;
    "title": string;
    "folderId": string;
    "order": number;
    "content": string;
    "createdAt": string;
    "updatedAt": string;
    "modifiedAt": number;
    "revision": number;
}

export interface NoteSummary {
    "id": string;
    "title": string;
    "folderId": string;
    "order": number;
    "createdAt": string;
    "updatedAt": string;
    "modifiedAt": number;
    "revision": number;
    "ciphertextHash"?: string;
    "tags"?: string[] | null;
    "attachmentIds": string[] | null;
    "outgoingLinks": string[] | null;
    "properties"?: { [_ in string]?: any } | null;
}

export interface NoteVersion {
    "revision": number;
    "title": string;
    "updatedAt": string;
}

export interface PortabilityResult {
    "notes": number;
    "folders": number;
    "attachments": number;
    "path": string;
}

/**
 * ReplaceResult summarizes a replace operation across notes.
 */
export interface ReplaceResult {
    "replacedNotes": number;
    "replacements": number;
}

export interface Session {
    "locked": boolean;
    "path": string;
    "vaultId": string;
    "noteCount": number;
}

export interface TimeDashboard {
    "projectCount": number;
    "tagCount": number;
    "totalSeconds": number;
    "averageDaySeconds": number;
    "projects": TimeDurationGroup[] | null;
    "tags": TimeDurationGroup[] | null;
    "tasks": TimeTaskGroup[] | null;
    "days": TimeDashboardDay[] | null;
}

export interface TimeDashboardDay {
    "localDate": string;
    "totalSeconds": number;
}

export interface TimeDurationGroup {
    "id": string;
    "name": string;
    "totalSeconds": number;
}

/**
 * TimeEntry is one logical tracking record. Empty EndedAtUTC means the entry
 * is currently running.
 */
export interface TimeEntry {
    "id": string;
    "name": string;
    "projectId"?: string;
    "tagIds": string[] | null;
    "startedAtUtc": string;
    "endedAtUtc"?: string;
    "createdAtUtc": string;
    "updatedAtUtc": string;
    "modifiedAt": number;
    "revision": number;
}

export interface TimeEntryFilters {
    "projectIds": string[] | null;
    "tagIds": string[] | null;
}

export interface TimeEntryRangeItem {
    "entry": TimeEntry;
    "startedAtUtc": string;
    "endedAtUtc": string;
    "totalSeconds": number;
}

export interface TimeEntryRangeResult {
    "entries": TimeEntryRangeItem[] | null;
    "days": TimeDashboardDay[] | null;
    "totalSeconds": number;
}

export interface TimeProject {
    "id": string;
    "name": string;
    "archivedAtUtc"?: string;
    "createdAtUtc": string;
    "updatedAtUtc": string;
    "modifiedAt": number;
    "revision": number;
}

export interface TimeTag {
    "id": string;
    "name": string;
    "archivedAtUtc"?: string;
    "createdAtUtc": string;
    "updatedAtUtc": string;
    "modifiedAt": number;
    "revision": number;
}

export interface TimeTaskGroup {
    "name": string;
    "totalSeconds": number;
    "entryCount": number;
}

export interface TimeTrackingCatalog {
    "projects": TimeProject[] | null;
    "tags": TimeTag[] | null;
}

export interface TimeTrackingConflict {
    "id": string;
    "kind": TimeTrackingConflictKind;
    "objectId": string;
    "message": string;
    "localEntry"?: TimeEntry | null;
    "remoteEntry"?: TimeEntry | null;
    "localProject"?: TimeProject | null;
    "remoteProject"?: TimeProject | null;
    "localTag"?: TimeTag | null;
    "remoteTag"?: TimeTag | null;
}

export enum TimeTrackingConflictKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TimeEntryEditConflict = "entry-edit",
    TimeProjectRenameConflict = "project-rename",
    TimeTagRenameConflict = "tag-rename",
    TimeEntryOverlapConflict = "entry-overlap",
    TimeActiveEntriesConflict = "active-entries",
};

export interface TrashItem {
    "id": string;
    "kind": string;
    "title": string;
    "deletedAt": string;
}

/**
 * VaultSettings contains portable preferences encrypted and synced with a vault.
 */
export interface VaultSettings {
    "theme": string;
    "journalLines": string;
    "editorFontSize": number;
    "dailyNoteFormat": string;
    "dailyNoteFolderId": string;
    "dailyTemplateNoteId": string;
    "autosaveIntervalSeconds": number;
    "autoLockMinutes": number;
    "sectionDefault": string;
    "modifiedAt": number;
}
