// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FindMatch describes a single occurrence of a query inside a note.
 */
export interface FindMatch {
    "noteId": string;
    "title": string;
    "field": string;
    "snippet": string;
    "offset": number;
    "matchLength": number;
}

export interface Folder {
    "id": string;
    "name": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * MergeResult summarizes a pull merge between the remote and local vault.
 */
export interface MergeResult {
    "pulledNotes": number;
    "updatedNotes": number;
    "deletedNotes": number;
    "pulledFolders": number;
    "deletedFolders": number;
    "upToDate": boolean;
}

export interface Note {
    "id": string;
    "title": string;
    "folderId": string;
    "content": string;
    "createdAt": string;
    "updatedAt": string;
    "modifiedAt": number;
    "revision": number;
}

export interface NoteSummary {
    "id": string;
    "title": string;
    "folderId": string;
    "createdAt": string;
    "updatedAt": string;
    "modifiedAt": number;
    "revision": number;
    "ciphertextHash"?: string;
}

/**
 * ReplaceResult summarizes a replace operation across notes.
 */
export interface ReplaceResult {
    "replacedNotes": number;
    "replacements": number;
}

export interface Session {
    "locked": boolean;
    "path": string;
    "vaultId": string;
    "noteCount": number;
}
