// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as githubsync$0 from "./internal/githubsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "./internal/vault/models.js";

export interface CloneVaultResult {
    "session": vault$0.Session;
    "message": string;
    "warning": string;
    "lastCommit": string;
    "linked": boolean;
}

export interface LastSession {
    "path": string;
    "theme": string;
}

/**
 * SyncResult summarizes a manual sync (pull then push) for the frontend.
 */
export interface SyncResult {
    "linked": boolean;
    "message": string;
    "warning": string;
    "branch": string;
    "lastCommit": string;
    "pull": githubsync$0.PullResult;
    "push": githubsync$0.PushResult;
    "merge": vault$0.MergeResult;
}
