// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as githubsync$0 from "./internal/githubsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "./internal/vault/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloneGitHubVault(parentPath: string, name: string, repositorySSH: string, privateKeyPath: string, branch: string, secret: string, repositoryPrivate: boolean): $CancellablePromise<$models.CloneVaultResult> {
    return $Call.ByID(3775142591, parentPath, name, repositorySSH, privateKeyPath, branch, secret, repositoryPrivate);
}

export function CloseVault(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(3979838393);
}

export function CopyVaultSecret(secret: string): $CancellablePromise<void> {
    return $Call.ByID(4028793456, secret);
}

export function CreateFolder(name: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(2923808401, name);
}

export function CreateNote(title: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(2924369193, title);
}

export function CreateNoteInFolder(title: string, folderID: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(414141426, title, folderID);
}

export function CreateVault(parentPath: string, name: string, secret: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(426481523, parentPath, name, secret);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(3131389926, id);
}

export function DeleteNote(id: string): $CancellablePromise<void> {
    return $Call.ByID(2663015250, id);
}

export function FindInNotes(query: string): $CancellablePromise<vault$0.FindMatch[] | null> {
    return $Call.ByID(1710427374, query);
}

/**
 * vault from the OS keychain. It is a no-op when the vault is not linked to
 * a keychain entry.
 */
export function ForgetVaultSecret(): $CancellablePromise<void> {
    return $Call.ByID(873520808);
}

export function GenerateVaultSecret(): $CancellablePromise<string> {
    return $Call.ByID(2346026114);
}

export function GetAttachment(noteID: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(3542621470, noteID, id);
}

export function GetLastSession(): $CancellablePromise<$models.LastSession> {
    return $Call.ByID(552484445);
}

export function GetLastVaultPath(): $CancellablePromise<string> {
    return $Call.ByID(1903514278);
}

export function GetNote(id: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(3086395091, id);
}

export function GetSession(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(1647850109);
}

export function GetSyncSettings(): $CancellablePromise<githubsync$0.SyncSettings> {
    return $Call.ByID(1559147273);
}

export function LinkGitHubVault(settings: githubsync$0.SyncSettings): $CancellablePromise<githubsync$0.LinkResult> {
    return $Call.ByID(4168621070, settings);
}

export function ListFolders(): $CancellablePromise<vault$0.Folder[] | null> {
    return $Call.ByID(509428674);
}

export function ListNotes(): $CancellablePromise<vault$0.NoteSummary[] | null> {
    return $Call.ByID(957394914);
}

export function LockVault(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(3610361410);
}

export function MoveNote(id: string, folderID: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(844302716, id, folderID);
}

export function OpenVault(path: string, secret: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(2142967671, path, secret);
}

/**
 * PullNow pulls and merges the remote vault snapshot without pushing back.
 */
export function PullNow(): $CancellablePromise<vault$0.MergeResult> {
    return $Call.ByID(4134315874);
}

export function QuitApplication(): $CancellablePromise<void> {
    return $Call.ByID(644217200);
}

export function ReadClipboardImage(): $CancellablePromise<string> {
    return $Call.ByID(3871424962);
}

export function RememberTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(3940625263, theme);
}

/**
 * RememberVaultSecret stores the open vault's secret in the OS keychain so
 * the user does not have to paste it again for the configured TTL. It must
 * be called only after a successful Open so the secret is known to be valid.
 */
export function RememberVaultSecret(): $CancellablePromise<void> {
    return $Call.ByID(3785816506);
}

export function RenameFolder(id: string, name: string): $CancellablePromise<vault$0.Folder> {
    return $Call.ByID(4192434379, id, name);
}

export function RenameVault(newName: string): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(2411141289, newName);
}

export function ReplaceAcrossNotes(find: string, replace: string, noteIDs: string[] | null): $CancellablePromise<vault$0.ReplaceResult> {
    return $Call.ByID(1753583, find, replace, noteIDs);
}

export function SaveAttachment(noteID: string, webpBase64: string): $CancellablePromise<string> {
    return $Call.ByID(1950368961, noteID, webpBase64);
}

export function SaveNote(id: string, title: string, content: string): $CancellablePromise<vault$0.Note> {
    return $Call.ByID(384107008, id, title, content);
}

export function SearchNotes(query: string): $CancellablePromise<vault$0.NoteSummary[] | null> {
    return $Call.ByID(2715025490, query);
}

export function SelectGitHubSSHKey(): $CancellablePromise<string> {
    return $Call.ByID(916216267);
}

export function SelectVaultDestinationFolder(): $CancellablePromise<string> {
    return $Call.ByID(1149411857);
}

export function SelectVaultFolder(): $CancellablePromise<string> {
    return $Call.ByID(3004577695);
}

/**
 * SyncNow performs a manual pull-merge-push against the linked GitHub
 * repository. Local notes newer than their remote counterpart are preserved;
 * remote notes newer than local replace the local copy.
 */
export function SyncNow(): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(3393855758);
}

export function TestGitHubConnection(settings: githubsync$0.SyncSettings): $CancellablePromise<githubsync$0.ConnectionResult> {
    return $Call.ByID(331598122, settings);
}

/**
 * TryUnlockRemembered attempts to unlock the last opened vault using a
 * secret remembered in the OS keychain. It returns ErrNoRememberedSecret
 * (or any other error) when the user must enter the secret manually; a
 * successful return yields an unlocked Session.
 */
export function TryUnlockRemembered(): $CancellablePromise<vault$0.Session> {
    return $Call.ByID(4124050448);
}

export function UnlinkGitHubSync(): $CancellablePromise<void> {
    return $Call.ByID(4085880674);
}
